general:
  buildTool: maven
  sonarTokenCredentialsId: sonartoken
  githubTokenCredentialsId: githubTokenCredentialsId
  productiveBranch: master
  verbose: true

steps:
  kanikoExecute:
    dockerfilePath: "Dockerfile"
  influxWriteData:
    influxServer: jenkins
    artifactVersion: "v1"
  sonarExecuteScan:
    host: 'http://172.17.0.1:9000'
    projectKey: 'my:test-maven-app'
    verbose: true